version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `diagrams-js` directory
    directory: "/diagrams-js"
    # Check for updates every week
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "javascript"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Set reviewers
    reviewers:
      - "hatemhosny"
    # Set assignees
    assignees:
      - "hatemhosny"
    # Allow up to 10 open pull requests
    open-pull-requests-limit: 10
    # Commit message prefix
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"

  # Enable version updates for npm in docs
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "documentation"
      - "javascript"
    reviewers:
      - "hatemhosny"
    assignees:
      - "hatemhosny"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps-docs)"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "hatemhosny"
    assignees:
      - "hatemhosny"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps-actions)"
      include: "scope"
